version: "3"
services:

  database_postgress:
    image: postgres:11-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}

    logging:
      driver: "none"
    volumes:
      - database_postgress-data:/var/lib/postgresql/data
  wiki:
    image: ghcr.io/requarks/wiki:2
    depends_on:
      - database_postgress
    environment:
      DB_TYPE: postgres
      DB_HOST: database_postgress
      DB_PORT: 5432
      DB_USER: ${POSTGRES_USER}
      DB_PASS: ${POSTGRES_PASSWORD}
      DB_NAME: ${POSTGRES_DB}
    ports:
      - "10080:3000"

volumes:
  database_postgress-data: