version: "3"
services:

  db:
    container_name: fettuccini-db
    image: postgres:11-alpine
    volumes:
      - db-data:/var/lib/postgresql/data
  wiki:
    image: ghcr.io/requarks/wiki:2
    depends_on:
      - db
    ports:
      - "9980:3000"

volumes:
  db-data: